---
- hosts: all
  tasks:
    - name: Install packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - curl
        - git
        - htop

    - name: Install pip
      become: yes
      easy_install:
        name: pip
        state: present

    - name: Install python packages
      become: yes
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - ranger-fm     

    - name: Install Rust
      become: yes
      shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
      changed_when: false

    # - name: Compile alacritty
