---
- hosts: all
  tasks:
    - name: Install packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - curl
        - git
        - htop

    - name: Install pip
      become: yes
      easy_install:
        name: pip
        state: present

    - name: Install python packages
      become: yes
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - ranger-fm  
